### ISSUE TITLE
not possible to make ctrl+n (new file)

### ISSUE THREAD

**Issue by yahyanouali** [reflash/zosftp-sublime#1]
Hi,

Please, I have a problem when I try to do CTRL+N (New File) after installing this plungin 👍 

Traceback (most recent call last):
  File "C:\Users\J16OI00\Sublime Text Build 3143\sublime_plugin.py", line 819, in run_
    return self.run(edit)
TypeError: run() missing 1 required positional argument: 'text'

Thanks in advance for your help.

**Comment by reflash** [comment]
Hello @iamyahya1, I've pushed some changes related to this issue, please try reinstalling the plugin and reload Sublime Editor.

**Comment by yahyanouali** [comment]
Hello @reflash , now it works very good, thanks a lot.

**Comment by yahyanouali** [comment]
Hi @reflash,
Do you know IBM z/os explorer for system Z : 

https://www.google.fr/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwjRirL6567YAhXCCMAKHUhoDpQQjRwIBw&url=https%3A%2F%2Fwww.ibm.com%2Fdeveloperworks%2Fcommunity%2Fblogs%2FJoeWinchester%2Fentry%2Fz_os_explorer_and_file_locking&psig=AOvVaw0IOlUW7fT-EQMe3QKqBgid&ust=1514622846843851

What do you think if we add this functionality to OpenCobolIDE (with python and PyQT), and then use your ftp API for submitting jobs and manipulating datasets?

Thanks in advance.

Yahya

**Comment by reflash** [comment]
@iamyahya1 yes, no problem, for that you just need one of the scripts, everything else can be easily changed to use with OpenCobolIDE. I have newer version of my ftp API, which I can place on GitHub after I'll return from vacation
